name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta el workflow diariamente a la medianoche
  workflow_dispatch:  # Permite ejecutar manualmente el workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Generar gráfico de serpiente
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Subir gráfico generado
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/

      - name: Agregar gráfico al perfil
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p assets
          mv dist/github-snake.svg assets/snake.svg
          git add assets/snake.svg
          git commit -m "Actualizar animación de contribución de serpiente"
          git push
